version: '3.3'

services:
    postgres:
        container_name: postgres
        image: postgres
        environment:
            - POSTGRES_PASSWORD=password
        ports:
            - "5432:5432"
        volumes:
            - ~/.docker-conf/postgresql/data/:/var/lib/postgresql/data"
    
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=marcosvianacdc@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=password
        ports:
            - "16543:80"
        depends_on:
            - postgres

    redis:
        container_name: redis
        image: redis:latest
        restart: always
        volumes:
            - /usr/local/etc/redis/redis.conf
        depends_on:
            - postgres

    backend:
        container_name: backend
        depends_on:
            - redis
            - postgres
        build: ./backend/
        restart: always
        ports:
            - "8000:8000"
        volumes:
            - ./backend/:/app/
        env_file:
            - ./backend/.env
        command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

    frontend:
        container_name: frontend
        depends_on:
            - backend
            - postgres
        build: ./frontend/
        restart: always
        ports:
            - "3000:8080"
        volumes:
            - ./frontend/:/frontend/
            - ./frontend/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
        command: npm run serve
    
    rabbitmq:
        container_name: rabbitmq
        depends_on:
            - redis
        image: rabbitmq:3-management
        hostname: "rabbitmq"
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        environment:
            - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=password
            - CLUSTERED=true