version: '3.3'

services:
    redis:
        image: redis:latest
        restart: always
        volumes:
            - /usr/local/etc/redis/redis.conf

    backend:
        depends_on:
            - redis
        build: ./backend/
        restart: always
        ports:
            - "8000:8000"
        volumes:
            - ./backend/:/app/
        env_file:
            - ./backend/.env
        command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

    frontend:
        depends_on:
            - backend
        build: ./frontend/
        restart: always
        ports:
            - "3000:8080"
        volumes:
            - ./frontend/:/frontend/
            - ./frontend/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
        command: npm run serve